version: '3.8'

services:
  lora-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - model-cache:/root/.cache/huggingface
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped

volumes:
  model-cache:
